#!/usr/bin/env bash
#Bash script that configures a new Ubuntu machine
#Install nginx on your web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root return a page that contains the string Holberton School

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
service nginx start
echo "Holberton School" > sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart