#!/usr/bin/env bash
#Redirect a page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart