#!/usr/bin/env bash
#Display an error page when can not find the page

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "38i error_page 404 /custom_404.html;\n location = /custom_404.html {\n  root /usr/share/nginx/html;\n internal;\n}\n" /etc/nginx/sites-available/default 
sudo service nginx restart