#!/usr/bin/env bash
#Install and configure HAproxy on lb-01 server.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo apt-get -y install haproxy
sudo sed -i "$ a\ \nfrontend firstbalance\n\tbind *:80\n\toption forwardfor\n\tdefault_backend webservers" /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\ \nbackend webservers\n\tbalance roundrobin\n\tserver 1508-web-01 34.74.50.241:80 check\n\tserver 1508-web-02 34.75.65.52:80 check" /etc/haproxy/haproxy.cfg
sudo service haproxy restart 