#!/usr/bin/env bash
#Advanced task https://intranet.hbtn.io/projects/255#task-1289
hbl_PID="/var/run/holbertonscript.pid"
echo $$ > "$hbl_PID"
trap 'echo I hate the kill command && rm $hbl_PID && exit' SIGTERM
trap "echo Y U no love me?!" SIGINT
trap 'rm $hbl_PID && exit' SIGQUIT
while true ;
do
	echo "To infinity and beyond"
	sleep 2
done;
