#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations

n=1;
while [ $n -le 10 ];
do
	if [ $n -eq 4 ]
	then
		echo "bad luck"
	elif [ $n -eq 8 ];
	then
		echo "good luck";
	else
		echo "Holberton School";
	fi
	n=$(( n+1 ));
done
