#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes

hour=0

while [ $hour -le 12 ];
do
	echo "Hour: $hour"
	for (( minutes=1; minutes<60; minutes++ ));
	do
		echo "$minutes"
	done
	hour=$(( hour+1 ));
done
